### PR TITLE
add the packaging metadata for the snap

### PR DESCRIPTION
**Pull request by EdgarPrada**

### CODE REVIEW

**Comment by EdgarPrada** [comment]
This package lets doge be in the Ubuntu Store. Go to snapcraft.io for more information

**Comment by thiderman** [comment]
I'm not familiar with what is considered `stable` over there, but doge has basically been without issues for years. It's the most stable project I've ever made. Maybe we should change that to `stable` from `devel`?

**Comment by EdgarPrada** [comment]
Sure, thiderman. Just changed it to stable. Regards

**Comment by thiderman** [comment]
Awesome! Thanks a lot! :dog2:

**Pull request merged**
